default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: '12345678'
  host: localhost

development:
  <<: *default
  database: ranking_deputados_development

test:
  <<: *default
  database: ranking_deputados_test

production:
  <<: *default
  database: ranking_deputados_production
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
